### ISSUE TITLE
Telescope 0.22.2

### ISSUE THREAD

**Issue by frabrunelle** [WebbROI/telescope-themes#1]
Would be nice to update this theme with the latest version of Telescope!

I tried to do it but I couldn't make it work.

Thank you very much.

**Comment by valgalin** [comment]
Thanks for the heads up! Will update it today. Please stay tuned.

**Comment by valgalin** [comment]
Hi @frabrunelle , Iris theme has been updated to the latest version of Telescope (v0.22.2).

**Comment by frabrunelle** [comment]
Thank you, it works great on the Telescope site I deployed for my friend: http://projects.conceptualrevolutions.com.
