### ISSUE TITLE
New telescope update

### ISSUE THREAD

**Issue by yochrepi** [WebbROI/telescope-themes#4]
Navigation breaks with the latest version of Telescope.

Would be nice if you made it compatible with tha last v0.24.00.

**Comment by valgalin** [comment]
Hi, we're currently working on the update. Stay tuned!

**Comment by valgalin** [comment]
Iris theme is now updated to work with latest Telescope v0.24.

Been busy with work-related stuff, so it took a while to finally released an update of the Iris theme.

Thanks!
