### ISSUE TITLE
v25 compatible?

### ISSUE THREAD

**Issue by Daz2345** [WebbROI/telescope-themes#5]
Hi valgalin
I love the iris theme that you've created - are you currently working on updating it for telescope v25?

**Comment by valgalin** [comment]
Hi Darren! Yes, we're currently working on updating it for Telescope v0.25. Stay tuned for updates. Thanks!

**Comment by Daz2345** [comment]
Thank you ever so much - massively appreciate your work!!

**Comment by Shurmonkey** [comment]
hi @valgalin Do you have some news about the iris update for Telescope 25.5?

Best Regards

**Comment by valgalin** [comment]
Hi, been busy with work stuff lately. I think I can find a time next week.
Will update you guys when I have a new version of the theme.

**Comment by hoanghadu** [comment]
We are waiting. Thank you very much.

**Comment by asennoussi** [comment]
I'm getting white page when installing the theme.

**Comment by valgalin** [comment]
Hi Aymane,

We're already 90% done updating the theme to be compatible with v0.25 of
Telescope. Stay tuned for updates. Thanks!

On Wed, Nov 11, 2015 at 10:39 PM, Aymane notifications@github.com wrote:

> I'm getting white page when installing the theme.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/WebbROI/telescope-themes/issues/5#issuecomment-155799832
> .

## 

_Regards,_
Val Galin

_Let's be friends! :)_
t: @valgalin http://twitter.com/valgalin
g+: +ValGalin https://plus.google.com/+ValGalin

**Comment by frabrunelle** [comment]
:+1: , my friend would also like to upgrade this theme to v0.25. Cheers!

**Comment by Daz2345** [comment]
Would it be possible for you to upload your current dev branch so that one of us may finish it and then submit a pull request, If time is still causing an issue re completion. Many Thanks.

**Comment by valgalin** [comment]
Hi guys, Iris theme is now compatible with v0.25 of the Telescope app.

**Comment by Daz2345** [comment]
omg Valgalin - thank you ever so much :+1: 
Your awesome!!
